version: "3.7"

services:
    server:
        container_name: bh_server
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - ${PORT}:${PORT}
        env_file:
            - .env
        depends_on:
            - db
    client:
        container_name: bh_client
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        ports:
            - ${CLIENT_PORT}:${CLIENT_PORT}
        environment:
            PORT: ${CLIENT_PORT}
            NODE_ENV: development
            REACT_APP_API_BASE_URL: ${BASE_URL}
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
    db:
        container_name: bh_postgres
        image: postgres
        environment:
            POSTGRES_USER: ${DOCKER_DB_USER}
            POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
            POSTGRES_DB: ${DOCKER_DB_NAME}
            PGDATA: /var/lib/postgresql/data
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: always
    adminer:
        container_name: bh_adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    pgdata:
