version: "3.7"

services:
    server:
        container_name: bh_server
        build: ./server
        environment:
            NODE_ENV: production
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - ${PORT}:${PORT}
        env_file:
            - .env
        depends_on:
            - db
    db:
        container_name: bh_postgres
        image: postgres
        environment:
            POSTGRES_USER: ${DOCKER_DB_USER}
            POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
            POSTGRES_DB: ${DOCKER_DB_NAME}
            PGDATA: /var/lib/postgresql/data
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: always
volumes:
    pgdata:
