version: "3.7"

services:
    server:
        container_name: bh_server
        build: .
        environment:
            NODE_ENV: production
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - db
    db:
        container_name: bh_db
        image: mysql
        environment:
            MYSQL_USER: ${DOCKER_DB_USER}
            MYSQL_PASSWORD: ${DOCKER_DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASSWORD}
            MYSQL_DATABASE: ${DOCKER_DB_NAME}
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
        restart: always
volumes:
    dbdata:
